In [42]:
def custom_accuracy(y_test,y_pred):
    right = 0

    l = len(y_pred)
    for i in range(0,l):
        if(abs(y_pred[i]-y_test[i]) <= 20):
            right += 1
    print((right/l)*100)

In [43]:
import pandas as pd
# Importing the dataset
mydata = pd.read_excel(r"C:\Users\pawan\Desktop\Project\all new\odidata.xlsx")

In [44]:
mydata

,mid,date,venue,inning,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,run_rate,runs_last_5,wickets_last_5,rr_last_5,striker,non-striker,total
0,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,0,0,0.1,0.00,0,0,0.00,0,0,301
1,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,0,0,0.2,0.00,0,0,0.00,0,0,301
2,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,4,0,0.3,8.00,4,0,8.00,0,0,301
3,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,6,0,0.4,9.00,6,0,9.00,0,0,301
4,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,6,0,0.5,7.20,6,0,7.20,0,0,301
5,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,6,0,0.6,6.00,6,0,6.00,0,0,301
6,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,6,0,1.1,5.14,6,0,5.14,0,0,301
7,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,6,0,1.2,4.50,6,0,4.50,0,0,301
8,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,6,0,1.3,4.00,6,0,4.00,0,0,301
9,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,7,0,1.4,4.67,7,0,4.67,0,0,301
10,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,8,0,1.5,4.80,8,0,4.80,1,0,301
11,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,D Langford-Smith,8,0,1.6,4.36,8,0,4.36,1,0,301
12,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,D Langford-Smith,9,0,1.7,4.50,9,0,4.50,1,1,301
13,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,10,0,2.1,5.00,10,0,5.00,1,1,301
14,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,10,0,2.2,4.62,10,0,4.62,1,1,301
15,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,11,0,2.3,4.71,11,0,4.71,1,1,301
16,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,DT Johnston,11,0,2.4,4.40,11,0,4.40,1,1,301
17,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,DT Johnston,12,0,2.5,4.50,12,0,4.50,2,1,301
18,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,12,0,2.6,4.24,12,0,4.24,2,1,301
19,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,16,0,2.7,5.33,16,0,5.33,5,2,301
20,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,17,0,3.1,5.67,17,0,5.67,5,2,301
21,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,17,0,3.2,5.37,17,0,5.37,5,2,301
22,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,21,0,3.3,6.30,21,0,6.30,6,5,301
23,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,21,0,3.4,6.00,21,0,6.00,6,5,301
24,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,21,0,3.5,5.73,21,0,5.73,6,5,301
25,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,21,0,3.6,5.48,21,0,5.48,6,5,301
26,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,EC Joyce,D Langford-Smith,21,0,3.7,5.25,21,0,5.25,6,5,301
27,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,25,0,4.1,6.00,25,0,6.00,9,6,301
28,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,29,0,4.2,6.69,29,0,6.69,13,6,301
29,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,32,0,4.3,7.11,32,0,7.11,16,6,301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335088,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Zahoor Khan,154,7,44.2,3.47,38,0,7.60,85,6,174
335089,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Zahoor Khan,154,7,44.3,3.46,38,0,7.60,85,6,174
335090,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Zahoor Khan,156,7,44.4,3.49,36,0,7.20,87,6,174
335091,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Zahoor Khan,157,7,44.5,3.50,36,0,7.20,88,6,174
335092,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Ehsan Nawaz,Zahoor Khan,158,7,44.6,3.51,37,0,7.40,88,7,174
335093,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Ehsan Nawaz,Mohammad Naveed,158,7,45.1,3.50,35,0,7.00,88,7,174
335094,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Ehsan Nawaz,Mohammad Naveed,160,7,45.2,3.53,33,0,6.60,88,9,174
335095,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Mohammad Naveed,161,7,45.3,3.54,32,0,6.40,89,9,174
335096,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Ehsan Nawaz,Mohammad Naveed,161,7,45.4,3.53,31,0,6.20,89,9,174
335097,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Ehsan Nawaz,Mohammad Naveed,163,7,45.5,3.56,33,0,6.60,89,11,174
335098,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Ehsan Nawaz,Mohammad Naveed,163,7,45.6,3.54,32,0,6.40,89,11,174
335099,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Zahoor Khan,163,7,46.1,3.53,32,0,6.40,89,11,174
335100,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Zahoor Khan,167,7,46.2,3.60,35,0,7.00,93,11,174
335101,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nizakat Khan,Zahoor Khan,167,8,46.3,3.59,34,1,6.80,93,11,174
335102,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Zahoor Khan,168,8,46.4,3.60,35,1,7.00,11,1,174
335103,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Ehsan Nawaz,Zahoor Khan,168,9,46.5,3.59,35,2,7.00,11,1,174
335104,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Zahoor Khan,169,9,46.6,3.60,36,2,7.20,2,0,174
335105,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Mohammad Naveed,169,9,47.1,3.58,35,2,7.00,2,0,174
335106,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Mohammad Naveed,169,9,47.2,3.57,33,2,6.60,2,0,174
335107,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Mohammad Naveed,169,9,47.3,3.56,33,2,6.60,2,0,174
335108,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Mohammad Naveed,169,9,47.4,3.55,32,2,6.40,2,0,174
335109,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Mohammad Naveed,169,9,47.5,3.53,32,2,6.40,2,0,174
335110,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Mohammad Naveed,169,9,47.6,3.52,32,2,6.40,2,0,174
335111,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Tanveer Ahmed,Zahoor Khan,170,9,48.1,3.53,27,2,5.40,2,1,174
335112,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Zahoor Khan,171,9,48.2,3.55,27,2,5.40,2,1,174
335113,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Zahoor Khan,171,9,48.3,3.54,26,2,5.20,2,1,174
335114,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Zahoor Khan,172,9,48.4,3.55,27,2,5.40,3,1,174
335115,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Tanveer Ahmed,Zahoor Khan,173,9,48.5,3.57,24,2,4.80,3,1,174
335116,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Tanveer Ahmed,Zahoor Khan,174,9,48.6,3.58,24,2,4.80,3,2,174
335117,1134,2017-01-26,Dubai International Cricket Stadium,1,Hong Kong,United Arab Emirates,Nadeem Ahmed,Zahoor Khan,174,10,48.7,3.56,24,3,4.80,3,2,174

In [45]:
mydata.shape

(335118, 18)

In [46]:
type(mydata)

pandas.core.frame.DataFrame

In [47]:
mydata.head(1)

,mid,date,venue,inning,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,run_rate,runs_last_5,wickets_last_5,rr_last_5,striker,non-striker,total
0,1,2006-06-13,"Civil Service Cricket Club, Stormont",1,England,Ireland,ME Trescothick,DT Johnston,0,0,0.1,0.0,0,0,0.0,0,0,301

In [48]:
X = mydata.iloc[:,[8,9,10,11,12,13,14,15,16]].values
y = mydata.iloc[:, 17].values

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 101)

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
lin = LinearRegression()
lin.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [55]:
y_pred = lin.predict(X_test)
print(lin.score(X_test,y_test)*100)

53.8698406973032

In [56]:
import numpy as np
new_prediction = lin.predict(sc.transform(np.array([[101,1,19,5.32,27,0,5.4,71,12]])))
print(new_prediction)

[291.497647]

In [57]:
from sklearn import metrics

In [58]:
metrics.mean_squared_error(y_test,y_pred)

1788.2415182101315

In [59]:
mse=np.sqrt(metrics.mean_squared_error(y_test,y_pred))

In [60]:
mse

42.287604782136

In [61]:
new_predict=lin.predict(sc.transform(np.array([[56,1,14.0,4,26,1,5.2,31,17]])))

In [62]:
print(new_predict)

[250.10323871]

In [63]:
import pickle
with open('lin.pkl', 'wb') as fid:
    pickle.dump(lin, fid,2)

In [71]:
file = open(r"C:\Users\pawan\Desktop\Project\all new\odidata.xlsx", errors='ignore')